services:
  db:
    image: postgres:17-alpine
    container_name: letzcollab-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - letzcollab-net

  backend:
    image: ghcr.io/peterkang98/backend:latest
    container_name: letzcollab-backend
    restart: always
    depends_on:
      - db
    env_file:
      # secrets.ENV_FILE
      - .env
    networks:
      - letzcollab-net

  frontend:
    image: ghcr.io/peterkang98/frontend:latest
    container_name: letzcollab-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # SSL 증명서 참조
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
      # nginx 설정 참조
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - letzcollab-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

networks:
  letzcollab-net:
    driver: bridge