services:
  db:
    image: postgres:17-alpine
    container_name: letzcollab-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - letzcollab-net

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}/backend:latest
    container_name: letzcollab-backend
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_ENC_KEY: ${JWT_ENC_KEY}
      JWT_ACCESS_EXP_TIME: ${JWT_ACCESS_EXP_TIME}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    depends_on:
      - db
    networks:
      - letzcollab-net

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY}/frontend:latest
    container_name: letzcollab-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # SSL 증명서 옮기기
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - letzcollab-net

networks:
  letzcollab-net:
    driver: bridge