decorator:
  datasource:
    p6spy:
      enable-logging: false
      multiline: false
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://db:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  data:
    redis:
      host: letzcollab-redis
      port: 6379
      password: ${REDIS_PASSWORD}

frontend:
  base-url: https://letzcollab.xyz