spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/letzcollab_db
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create

  mail:
    properties:
      mail:
        debug: true