spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/letzcollab_db
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  sql:
    init:
      # DB에 시드 데이터 넣기 전에는 always로
      mode: never
      data-locations: classpath:sql/seed.sql

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      # DB에 시드 데이터 넣기 전에는 create로, defer-datasource-initialization은 true로
      ddl-auto: none
    defer-datasource-initialization: false

  mail:
    properties:
      mail:
        debug: true

cookie:
  secure: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: always