decorator:
  datasource:
    p6spy:
      enable-logging: false
      multiline: false
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://db:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: mail
    port: 25
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            required: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

frontend:
  base-url: https://letzcollab.xyz

cookie:
  secure: true